export const GET_CURRENT_LOCATION_START = "GET_CURRENT_LOCATION_START";
export const GET_CURRENT_LOCATION_OK = "GET_CURRENT_LOCATION_OK";
export const GET_CURRENT_LOCATION_FAIL = "GET_CURRENT_LOCATION_FAIL";

export const GET_BATHROOMS_START = "GET_BATHROOMS_START";
export const GET_BATHROOMS_OK = "GET_BATHROOMS_OK";
export const GET_BATHROOMS_FAIL = "GET_BATHROOMS_FAIL";

export const NEXT_PAGE = "NEXT_PAGE";
export const CHANGE_PAGE_OK = "CHANGE_PAGE_OK";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const FIRST_PAGE = "FIRST_PAGE";
export const FETCH_PAGE_FAIL = "FETCH_PAGE_FAIL";
