export const GET_CURRENT_LOCATION_START = "GET_CURRENT_LOCATION_START";
export const GET_CURRENT_LOCATION_OK = "GET_CURRENT_LOCATION_OK";
export const GET_CURRENT_LOCATION_FAIL = "GET_CURRENT_LOCATION_FAIL";
